<?php

/**
 * @file
 * Contains ibudakaup_helper.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ibudakaup_helper_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ibudakaup_helper module.
    case 'help.page.ibudakaup_helper':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper function for the website Íbúðakaup.is') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_editor_js_settings_alter
 */
function ibudakaup_helper_editor_js_settings_alter(array &$settings) {
  foreach ($settings['editor']['formats'] as $name => $value) {
    $settings['editor']['formats'][$name]['editorSettings']['allow_empty'] = true;
  }
}