<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
function ibudakaup_preprocess_block(&$variables) {
  if($variables['attributes']['id'] == 'block-omaravegg') {
    $image_obj = $variables['content']['field_mynd'][0]['#media'];

    if (!empty($image_obj)) {
      $variables['hero_image'] = \Drupal\image\Entity\ImageStyle::load('1600x1200')->buildUrl($image_obj->field_mynd->entity->getFileUri());
    }
  }
}